ALTER TABLE tenants ADD COLUMN IF NOT EXISTS favicon_url TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS bg_color VARCHAR(50);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS font_family VARCHAR(100);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS custom_email VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS use_custom_email BOOLEAN DEFAULT false;
